queue: 'Hosted VS2017'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: 3.0.100-preview9-014004
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: src/Blazor.Extensions.Canvas.JS
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      packagesToPack: 'src/Blazor.Extensions.Canvas/*.csproj'
      configuration: '$(buildConfiguration)'
      versioningScheme: byPrereleaseNumber
      majorVersion: '0'
      minorVersion: '1'
      patchVersion: '0'