queue: 'Hosted VS2017'

variables:
  buildConfiguration: 'Release'

steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: src/Blazor.Extensions.Canvas.JS

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      packagesToPack: 'src/Blazor.Extensions.Canvas/*.csproj'
      packDirectory: '$(build.artifactStagingDirectory)'
      configuration: '$(buildConfiguration)'
      versioningScheme: byEnvVar
      versionEnvVar: Version

  - task: NuGetCommand@2
    inputs:
      command: push
      packagesToPush: '$(build.ArtifactStagingDirectory)/**/*.nupkg;!$(build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      publishFeedCredentials: 'BlazorExtensions'
      nuGetFeedType: external
      versioningScheme: byEnvVar
      versionEnvVar: Version